In [57]:
# import numpy as np
# a = np.random.random((3, 3))  # 生成一个三行三列的随机数并存储在数组中
# print(a)
# np.save("./tmp/tmp.npy", a)  # save方法可以保存文件为npy格式，前面为保存的路径，后面是要保存的数组
# a.sort(axis = 0)  # sort方法可以对数组进行排序，axis值为1表示每一行进行排序，axis为0表示每一列进行排序
# print(a)
# b = np.array([4, 8, 2])
# b.sort()  # 默认按顺序进行排列
# print(b)
# c = b.argsort()  # argsort方法进行排序，默认为顺序排序，返回的是对应数值的下标
# print(c)
# d = np.repeat(b, 2)  # repeat方法将每一个元素重复一次，这种重复为元素连续重复
# print(d)
# e = np.tile(b, 2)  # tile方法可以将一个数组按整个数组进行重复
# print(e)
# f = np.unique(e)  # unique方法可以将数组进行元素去重复操作  
# print(f)

[4 4 8 8 2 2]
[4 8 2 4 8 2]
[2 4 8]


In [45]:
# b = np.random.randn(2, 2)  # 随机生成一个两行两列的数组，数值可以为负数
# print(b)
# np.savez("./tmp/tmp2.npz", a, b)  # savez方法可以将多个内容保存到一个文件下

In [46]:
# a = np.load("./tmp/tmp.npy")  # load方法可以直接提取npy的内容，但是无法直接读取npz的内容
# print(a)
# b = np.load("./tmp/tmp2.npz")
# c = b.files  # files方法可以查看npz文件下有几个内容
# print(c)
# d = b["arr_0"]  # 使用索引可以查看对应的内容
# print(d)

In [47]:
# np.savetxt("./tmp/tmp3.txt", a)  # savetxt可以将内容保存为txt文件的格式
# np.loadtxt("./tmp/tmp3.txt")  # loadtxt方法可以直接查看txt文件内容
# np.genfromtxt("./tmp/tmp3.txt")  # genfromtxt方法也可以直接查看txta文件内容

#### 任务：读取数据并进行相关的操作

In [77]:
import numpy as np
data = np.loadtxt("./data/data/iris_sepal_length.csv")  # 读取指定的文件
data.sort()  # 按顺序序列进行排序
data = np.unique(data)  # 进行去重操作
print(data)
count = np.sum(data)  # 对数组中的元素进行求和
print(count)
cumcount = np.cumsum(data)  # 对数组进行求累计和，就是元素依次相加
print(cumcount)
print(np.mean(data))  # 求平均值
print(np.std(data))  # 求标准差
print(np.var(data))  # 求方差
print(np.max(data))  # 求最大值
print(np.min(data))  # 求最小值

[4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.
 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6 7.7 7.9]
210.39999999999998
[  4.3   8.7  13.2  17.8  22.5  27.3  32.2  37.2  42.3  47.5  52.8  58.2
  63.7  69.3  75.   80.8  86.7  92.7  98.8 105.  111.3 117.7 124.2 130.8
 137.5 144.3 151.2 158.2 165.3 172.5 179.8 187.2 194.8 202.5 210.4]
6.011428571428571
1.0289443768310533
1.0587265306122449
7.9
4.3
